import Image from 'next/image'
import '../globals.css'
import { Montserrat } from "next/font/google"
import carbon from '../assets/carbon.jpg'

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ['100', '300', '400', '600', '900'],
    style: ["italic", "normal"],
})

export default function About() {

    return (
        <div className={montserrat.className}>
            <h1 className="about-heading">
                What are Carbon Footprints? 👣
            </h1>
            <div className='text-zone'>
                <div className='carbon-text'>
                    <p className='floating'>
                        A carbon footprint is the total amount of greenhouse gases (including carbon
                        dioxide and methane) that are generated by our actions.
                    </p>

                    <p className='floating'>
                        The average carbon footprint for a person in the United States is 16 tons,
                        one of the highest rates in the world. Globally, the average carbon footprint
                        is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global
                        temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.
                    </p>

                    <p className='floating'>
                        Lowering individual carbon footprints from 16 tons to 2 tons doesn't happen
                        overnight! By making small changes to our actions, like eating less meat, taking
                        fewer connecting flights and line drying our clothes, we can start making a big difference.
                    </p>
                </div>
                <Image src={carbon} alt='' width={500} />
            </div>
        </div>
    )
}