import './globals.css'
import Picture1 from './assets/Picture1.jpg'
import pic2 from './assets/pic2.jpg'
import pic3 from './assets/pic3.jpg'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <section className="wrapper">
        <div className="container">

          <div className="grid-cols-2">
            <div className="grid-item-1">
              <h1 className="main-heading">
                Presenting <span>Earth Impact</span>
                <br />

              </h1>
              <p className="info-text">
                Small steps for a big impact: track and reduce your carbon footprint with Earth Impact
              </p>

              <div className="btn_wrapper">
                <button className="btn view_more_btn">
                  Calculate now <i className="ri-arrow-right-line"></i>
                </button>

                <button className="btn documentation_btn" href="#about-content">Learn More</button>
              </div>
            </div>
            <div className="grid-item-2">
              <div className="team_img_wrapper">
                <Image src={Picture1} alt="team-img" />
              </div>
            </div>
          </div>
        </div>
      </section>

      <hr className="featurette-divider" />

      <section className="about">
        <div className="container">
          <div className="about-content">
            <div className="about-image">
              <Image src={pic2} alt="About Us Image" />
            </div>
            <div className="about-text">
              <h2>About Earth Impact</h2>
              <p>Earth Imapct is a platform that aims to bring awareness among people about how carbon emissions affect our lives, calculating your contributions to it and letting people pledge </p>
            </div>
          </div>
        </div>
      </section>

      <section className="about">
        <div className="container">
          <div className="about-content">
            <div className="about-text">
              <h2><strong>What is a carbon footprint?</strong></h2>
              <p>A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.<br /><br />

                The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average carbon footprint is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.<br /><br />

                Lowering individual carbon footprints from 16 tons to 2 tons doesn't happen overnight! By making small changes to our actions, like eating less meat, taking fewer connecting flights and line drying our clothes, we </p>
            </div>
            <div className="about-image">
              <Image src={pic3} alt="Carbon Footprint" />
            </div>
          </div>
        </div>
      </section>

      <hr className="featurette-divider" />

      <section className="wrapper">
        <div className="container" data-aos="fade-up" data-aos-duration="1000">
          <div className="grid-cols-3">
            <div className="grid-col-item">
              <div className="icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 9v11a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V9" /><path d="M9 22V12h6v10M2 10.6L12 2l10 8.6" /></svg>
              </div>
              <div className="featured_info">
                <span>Built for individuals </span>
                <p>
                  Earth Impact is built with individuals in mind, aiming for small households for the time being.
                </p>
              </div>
            </div>
            <div className="grid-col-item">
              <div className="icon">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M17 14v6m-3-3h6M6 10h2a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v2a2 2 0 002 2zm10 0h2a2 2 0 002-2V6a2 2 0 00-2-2h-2a2 2 0 00-2 2v2a2 2 0 002 2zM6 20h2a2 2 0 002-2v-2a2 2 0 00-2-2H6a2 2 0 00-2 2v2a2 2 0 002 2z"
                  />
                </svg>
              </div>
              <div className="featured_info">
                <span>Easy to use</span>
                <p>
                  With a simple, straightforward approach, you can find your carbon footprint in less than a minute!
                </p>
              </div>
            </div>

            <div className="grid-col-item">
              <div className="icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
              </div>
              <div className="featured_info">
                <span>Compete with others!</span>
                <p>
                  Earth Impact tells you standings among other people in the same category so you can see who's the best at saving mother Earth!

                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
